#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-getopt
Version  : 1.20.4
Release  : 53
URL      : https://cran.r-project.org/src/contrib/getopt_1.20.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/getopt_1.20.4.tar.gz
Summary  : C-Like 'getopt' Behavior
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-getopt-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
'#!' shebang scripts that accept short and long flags/options.
    Many users will prefer using instead the packages optparse or argparse
    which add extra features like automatically generated help option and usage,
    support for default values, positional argument support, etc.

%package license
Summary: license components for the R-getopt package.
Group: Default

%description license
license components for the R-getopt package.


%prep
%setup -q -n getopt
pushd ..
cp -a getopt buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1696264520

%install
export SOURCE_DATE_EPOCH=1696264520
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-getopt
cp %{_builddir}/getopt/COPYING %{buildroot}/usr/share/package-licenses/R-getopt/4cc77b90af91e615a64ae04893fdffa7939db84c || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

## Remove excluded files
rm -f %{buildroot}*/usr/lib64/R/library/getopt/exec/example.R
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/getopt/DESCRIPTION
/usr/lib64/R/library/getopt/INDEX
/usr/lib64/R/library/getopt/Meta/Rd.rds
/usr/lib64/R/library/getopt/Meta/features.rds
/usr/lib64/R/library/getopt/Meta/hsearch.rds
/usr/lib64/R/library/getopt/Meta/links.rds
/usr/lib64/R/library/getopt/Meta/nsInfo.rds
/usr/lib64/R/library/getopt/Meta/package.rds
/usr/lib64/R/library/getopt/NAMESPACE
/usr/lib64/R/library/getopt/NEWS.md
/usr/lib64/R/library/getopt/R/getopt
/usr/lib64/R/library/getopt/R/getopt.rdb
/usr/lib64/R/library/getopt/R/getopt.rdx
/usr/lib64/R/library/getopt/help/AnIndex
/usr/lib64/R/library/getopt/help/aliases.rds
/usr/lib64/R/library/getopt/help/figures/logo.png
/usr/lib64/R/library/getopt/help/figures/logo.svg
/usr/lib64/R/library/getopt/help/getopt.rdb
/usr/lib64/R/library/getopt/help/getopt.rdx
/usr/lib64/R/library/getopt/help/paths.rds
/usr/lib64/R/library/getopt/html/00Index.html
/usr/lib64/R/library/getopt/html/R.css
/usr/lib64/R/library/getopt/tests/run-all.R
/usr/lib64/R/library/getopt/tests/testthat/test-getopt.R

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-getopt/4cc77b90af91e615a64ae04893fdffa7939db84c
